### ISSUE TITLE
Top texture grass is not like vanilla

### ISSUE THREAD

**Issue by lebonq** [lebonq/Automatic-Path#5]
I have absolutly no idea what cause this bug

**Comment by Fourmisain** [comment]
I think this is the right issue.
I noticed that I could see Grass Blocks converting to Path after stepping on them once (looking down or in F5).

This issue is due to texture variation, which for Grass Blocks seems to be rotation, e.g. look at this screenshot:
![texture variation](https://user-images.githubusercontent.com/8464472/121827470-67a95280-ccbc-11eb-97ef-138e5c9bba4c.png)

the white boxed ones are Path, the top left one is a Grass Block, Grass Blocks can have different rotations but Path can only have one.

So ideally, the same variation/rotation from the original Grass Block should be applied to the Path block as well.

**Comment by lebonq** [comment]
Thanks for your help ! So I dig a little into this and you are right there is a random rotation on the top texture of grass. 
In order to fix this I did the same rotation of the Mojang's grass block in my path block. (in the blockstates file)
BUT if I do this, I modify the block's states so all the block already in place in old world will disepeared.

**Comment by Fourmisain** [comment]
I did some testing on this and the first time I changed the blockstates (by adding the snowy=false and snowy=true states), I did indeed find Path blocks wouldn't load.

So I added the new state to the state manager and set a default state too and the Path blocks seemed to load just fine.
The odd thing is: After I went back and undid the last two steps for testing and restoring the world from a backup, I couldn't reproduce the issue anymore - really not sure what happened there.

Either way, I think I found an easy compatible way that adds the rotation variants and it looks like it fixes the visible rotation change when stepping on grass blocks too!
